### ISSUE TITLE
Replace <script> with <script src="">

### ISSUE THREAD

**Issue by Aaron-Lathrop** [nisarhassan12/portfolio#1]
`<script>
    const navigation__checkbox = document.querySelector(
      ".navigation__checkbox"
    );
    const navigation__links = document.querySelectorAll(".navigation__link");
    for (let i = 0; i < navigation__links.length; ++i) {
      navigation__links[i].addEventListener("click", () => {
        navigation__checkbox.checked = false;
      });
    }
  </script>`

While having this in your html works, moving this to it's own javascript file and including it with a <script src=""> tag would make your code cleaner.

**Comment by nisarhassan12** [comment]
Thanks @Aaron-Lathrop for your great suggestion I have this script tag intentionally here because if i move this to another file then this will increase the number of HTTP requests for the client by 1 and I don't want to do that for performance reasons.
