### ISSUE TITLE
Styling problems

### ISSUE THREAD

**Issue by mehrdad-shokri** [nisarhassan12/portfolio#6]
running application both in ``dev`` and ``prod`` doesn't load stylesheets.  
Also in ``index.html`` there is no link to stylesheets. Am I missing something?

**Comment by mehrdad-shokri** [comment]
Just added ``import '../scss/main.scss'`` to ``src/js/index.js`` I don't know why it's removed in [this commit](https://github.com/nisarhassan12/portfolio/commit/8674f4b726d223c27598443a58f525f40841d8d3)

**Comment by nisarhassan12** [comment]
Thanks! @mehrdad-shokri  Let me check :)

**Comment by nisarhassan12** [comment]
Thanks! @mehrdad-shokri. It will hopefully work now I have fixed this. 
the commit that you mentioned caused the problem.

**Comment by mehrdad-shokri** [comment]
@nisarhassan12 yeah, thank you!
